#!/bin/bash

##########################
#                        #
#   The PBS directives   #
#                        #
##########################

# Define the shell in which your jobs should run.
#PBS -S /bin/bash
#PBS -N cellsnp-lite
#PBS -o out.$PBS_JOBNAME."$capture".$PBS_JOBID
#PBS -e err.$PBS_JOBNAME."$capture".$PBS_JOBID
#PBS -j oe
#PBS -q batch
#PBS -A canc2
#PBS -l nodes=1:ppn=8
#PBS -l mem=16GB
#PBS -l walltime=36:00:00
#PBS -m be
#PBS -M anson.wong@mcri.edu.au

### END OF PBS OPTIONS



##########################################
#                                        #
#   Output some useful job information.  #
#                                        #
##########################################

echo ------------------------------------------------------
echo -n 'Job is running on node '; cat $PBS_NODEFILE
echo ------------------------------------------------------
echo PBS: qsub was run on $PBS_O_HOST
echo PBS: originating queue is $PBS_O_QUEUE
echo PBS: executing queue is $PBS_QUEUE
echo PBS: working directory is $PBS_O_WORKDIR
echo PBS: execution mode is $PBS_ENVIRONMENT
echo PBS: job identifier is $PBS_JOBID
echo PBS: job name is $PBS_JOBNAME
echo PBS: node file is $PBS_NODEFILE
echo PBS: current home directory is $PBS_O_HOME
echo PBS: temporary directory on node is $TMPDIR
echo PBS: PATH = $PBS_O_PATH
echo ------------------------------------------------------


runJob()
{
    echo ----------------------
	echo Executing Job Steps
    echo ----------------------

    /bin/echo "going to sleep to simulate job run time"
    sleep 10
    /bin/echo "woken up again. sooooo refreshed :)"

    echo ----------------------
}



# ----- Notifies you that your job terminated early ----- #
earlyTermination()
{
    echo ' '
    echo ' ############ WARNING:  EARLY TERMINATION #############'
    echo ' '
}
trap 'earlyTermination;' 2 9 15
# ------------------------------------------------------- #

# Change to the temporary folder created for this job on the comp node
#cd $TMPDIR

# Run the steps required to complete this job
cd $workDIR
sh code/cellsnp-lite.sh "$capture"

exit

